resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 100
      minimumNumberOfCalls: 10
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
  instances:
    myService:
      baseConfig: default
   
    
spring:
  application:
    name: CircuitBreaker-1

    
server:
  port: 4444